/** English UI copy. Grade 2 for chrome, grade 1 for tutorial lines. */
export const en = {
  appName: 'TypeDrop',
  tagline: 'Catch the words. Keep your eyes on the screen.',
  start: 'Start',
  howTo: 'How to Play',
  profiles: 'Profiles',
  leaderboard: 'Leaderboard',
  home: 'Home',
  stats: 'Stats',
  settings: 'Settings',
  help: 'Help',
  customize: 'Customize',
  back: 'Back',
  continue: 'Continue',
  nextFinger: 'Next finger',
  play: 'Play',
  pause: 'Pause',
  resume: 'Resume',
  retry: 'Try again',
  nextLevel: 'Next level',
  quit: 'Quit',
  save: 'Save',
  cancel: 'Cancel',
  close: 'Close',
  confirm: 'Confirm',
  delete: 'Delete',
  reset: 'Reset progress',
  erase: 'Erase all data',
  clearBoard: 'Clear device board',
  privacyTitle: 'A note for grown-ups',
  privacyBody: 'TypeDrop keeps profiles on this device only. Children do not need an email. There is no chat and no ads. Speech uses the computer voice, not a microphone. You can download stats or erase everything in Settings.',
  privacyAccept: 'Continue',
  layoutWarn: 'This keyboard may not be US QWERTY. TypeDrop teaches QWERTY finger places.',
  offline: 'You are offline. Saved lessons still play on this device.',
  createTitle: 'New player',
  nameLabel: 'Display name',
  nameHint: 'First name or nickname. 2 to 12 letters.',
  avatarLabel: 'Pick an avatar',
  sceneLabel: 'Pick a scene',
  pinLabel: 'Grown-up pin (optional)',
  pinHint: '4 digits. Used only to delete a profile or reset progress on this device.',
  create: 'Create profile',
  switchPlayer: 'Switch player',
  manageProfiles: 'Manage profiles',
  noProfiles: 'No players yet. Create one to start the lesson.',
  maxProfiles: 'This device already has 6 players.',
  deleteTitle: 'Delete this player?',
  deleteType: 'Type the display name to delete.',
  pinPrompt: 'Enter the 4-digit pin.',
  pinWrong: 'That pin does not match.',
  welcome: 'We will put both hands on the keyboard and keep our eyes on the screen.',
  postureTitle: 'Sit like this',
  postureBody: 'Feet on the floor. Shoulders soft. Screen at your eyes. Wrists float. Fingers curve.',
  postureAdult: 'Grown-up helper: a chair that lets both feet rest, and a screen that does not make them look down.',
  homeRowTitle: 'Find the home row',
  homeRowBody: 'Left hand on A S D F. Right hand on J K L and the semicolon. Thumbs on the space bar.',
  bumps: 'Feel the little bumps. Those are home.',
  restTitle: 'Place your fingers now',
  restBody: 'Press the space bar when both thumbs are ready.',
  restHelp: 'Press the space bar with both thumbs when you are ready.',
  tryFinger: 'Try the finger that is glowing.',
  wrongKey: 'is the wrong key.',
  letterTitle: 'Type the letter you see',
  reachTitle: 'Now reach a little',
  retryTitle: 'Let us try the tricky ones again',
  gradTitle: 'You did it',
  gradEyes: 'Keep your eyes on the screen. The keys will still be there.',
  playLevel1: 'Go to Home',
  skipLesson: 'Skip lesson',
  exitReplay: 'Stop replay',
  replayLesson: 'Replay the lesson',
  practiceHome: 'Practice home row',
  letterGarden: 'Letter Garden',
  homeRowOnly: 'Home Row Only',
  replayLevel: 'Replay a level',
  locked: 'Locked',
  lives: 'Lives',
  score: 'Score',
  combo: 'Combo',
  wpm: 'WPM',
  hideKeys: 'Hide keys',
  showKeys: 'Show keys',
  paused: 'Paused',
  quitAsk: 'Leave this round? This try will not be saved.',
  reloadAsk: 'Reload the page? This round will not be saved.',
  reload: 'Reload',
  stay: 'Keep playing',
  resultsWin: 'Nice catching',
  resultsLose: 'The words got there first',
  loseKind: 'You can try this level again. Nothing you already earned is lost.',
  words: 'Words',
  accuracy: 'Accuracy',
  comboPeak: 'Best combo',
  cpm: 'Letters per minute',
  time: 'Time',
  stars: 'Stars',
  fingerHint: 'Finger tip',
  myRecords: 'My records',
  thisDevice: 'This device',
  boardEmpty: 'Play a level to land on the board.',
  boardNote: 'This board stays on this computer. No internet ranking.',
  sessions: 'Sessions',
  wordsTyped: 'Words typed',
  bestWpm: 'Best WPM',
  avgAccuracy: 'Average accuracy',
  playTime: 'Play time',
  tutorialDate: 'Lesson finished',
  recent: 'Last 10 rounds',
  badges: 'Badges',
  noRuns: 'No rounds yet.',
  level: 'Level',
  sound: 'Sound',
  volume: 'Volume',
  music: 'Music',
  sfx: 'Sound effects',
  quiet: 'Quiet mode',
  quietHint: 'No speech, softer music, shorter cheers.',
  motion: 'Reduced motion',
  contrast: 'High contrast tiles',
  keys: 'On-screen keyboard',
  keysAuto: 'Auto (levels 1–2)',
  keysOn: 'On',
  keysOff: 'Off',
  fingerColors: 'Finger colors',
  textSize: 'Text size',
  textDefault: 'Default',
  textLarge: 'Large',
  dysFont: 'Atkinson Hyperlegible font',
  flashes: 'Mute extra flashes',
  speech: 'Speak letters in the lesson',
  speechHint: 'Uses the computer voice. The microphone stays off.',
  flip: 'Left-handed hint order',
  flipHint: 'Shows the right hand first. The keys do not move.',
  grownup: 'Grown-up tools',
  downloadJson: 'Download my stats (JSON)',
  exportRuns: 'Export my runs (CSV)',
  exportLevels: 'Export level records (CSV)',
  exportDevice: 'Export device board (CSV)',
  exportResearch: 'Export research log (CSV)',
  exportHelp: 'CSV opens in a spreadsheet. The research log has no display names.',
  eraseAsk: 'Type ERASE to remove every TypeDrop profile on this device.',
  resetAsk: 'Reset stars, scores, and stats for this player?',
  clearAsk: 'Clear the device board? Stars and profiles stay.',
  suggestHome: 'Practice home row is a good warm-up.',
  eyesUp: 'Eyes up',
  helpHands: 'Rest both hands on the home row. Left fingers on A S D F. Right fingers on J K L and semicolon. Thumbs on space.',
  helpPlay: 'Type the lowest word, the one with the blue ring. Gold letters are the ones you already typed. If a word lands, you lose a life. Three lands ends the round.',
  helpStars: 'Finish a level to earn a star and open the next one. A miss does not take stars you already earned.',
  helpKeys: 'Backspace fixes the word you are on. Escape pauses. The address bar is not part of the game.',
  sceneNext: 'Scene',
  tutorialSteps: ['Welcome', 'Posture', 'Home row', 'Fingers', 'Hands ready', 'Home test', 'Reach test', 'Done'],
};
